version: "3.9"
services:
  permessi-asl:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - /volume1/permessi:/app/output   # NAS path — user can change this
